# Generated by Django 4.2.27 on 2026-02-11 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='created_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='number_answer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='question_media/'),
        ),
        migrations.AddField(
            model_name='question',
            name='media_kind',
            field=models.CharField(choices=[('none', 'None'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('choice_single', 'Single choice'), ('choice_multi', 'Multi choice'), ('input_text', 'Text input'), ('input_number', 'Number input'), ('tf', 'True/False choice')], default='choice_single', max_length=20),
        ),
    ]
