# Generated by ChatGPT patch 9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0005_question_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="delivery_mode",
            field=models.CharField(choices=[("self_paced", "Self-paced"), ("live", "Live")], default="self_paced", max_length=20),
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="learning_goal",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="numeric_tolerance",
            field=models.FloatField(default=0.0),
        ),
    ]
