# Generated by ChatGPT patch: quiz/trivia split and search filters

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0006_patch9_question_metadata_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="kind",
            field=models.CharField(
                choices=[("quiz", "Quiz"), ("trivia", "Trivia")],
                db_index=True,
                default="quiz",
                help_text="quiz means academic quiz; trivia means entertainment quiz",
                max_length=12,
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(fields=["kind", "publish_status", "visibility"], name="quizzes_qui_kind_220797_idx"),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(fields=["difficulty", "created_at"], name="quizzes_qui_difficu_fbd022_idx"),
        ),
    ]
